n_nodes = 2
max_number_of_attempts = 10
path_to_save = "./results/"
path_server_data = "./data/server_data.csv"
path_file_with_fields_to_use_for_the_train = "./config/fields_ml.txt"
ml_model_name = "SVC"
[ml_algorithm_config]
c = 1
kernel = 'rbf'
degree = 3
gamma = 'scale'
max_iter = 1
